version: '3'

services:
  mongodb:
    container_name: user_mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=user-service
    ports:
      - 27017:27017
    volumes:
      - user_mongo:/data/db

  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      MONGODB_HOST: user_mongo
      MONGODB_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGODB_DB: user-service
    depends_on:
      - mongodb
    volumes:
      - .:/code
    ports:
      - "8000:8000"

volumes:
  user_mongo:
