version: '3'

services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_INITDB_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD}"
      - MONGO_INITDB_DATABASE=user-service
    ports:
      - 27017:27017

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
