# This is a basic workflow to help you get started with Actions

name: Create Project Cards

on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.ACTIONS_PAT }}
          project-location: mindtastic
          project-name: mindtastic Main Board
          column-name: To Do
